### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by DruidVorse**

### CODE REVIEW

**Review by Lojemiru — CHANGES_REQUESTED** [review]
For the time being we're unaware of Far Cry 3 Blood Dragon and System Shock remake content levels; please remove and we'll approve.

**Comment by DruidVorse** [comment]
ok, they are now removed from the list.

**Comment by Miepee** [comment]
Considering the brutality of Doom and their suggested age ratings, I personally disagree with putting them on the list.

**Comment by DruidVorse** [comment]
updated the list and removed the Doom games

**Pull request merged**
